### PR TITLE
Add support for TestTransaction routines

### PR DESCRIPTION
**Pull request by msjohns1**

### CODE REVIEW

**Comment by EvanHahn** [comment]
Could you explain why you need this?

**Comment by msjohns1** [comment]
On 03/08/2017 03:46 PM, Evan Hahn wrote:
> Could you explain why you need this?

Because the functionality exists in the Ruby library, and is documented
as such. When we went to use it based on Ruby docs, it didn't exist. So
this fills in the missing functionality, presumably developed after the
Perl library was deprecated.

**Comment by EvanHahn** [comment]
@msjohns1 Would you be comfortable working with @singingfish on an unofficial fork? See [my comment in another PR](https://github.com/braintree/braintree_perl/pull/21#issuecomment-285773432).

**Comment by singingfish** [comment]
Happy to collaborate on an endorsed community fork probably originating from here https://github.com/singingfish/braintree_perl.  Note the module will almost certainly be renamed to WebService::Braintree.

**Comment by EvanHahn** [comment]
@msjohns1 We're going to close this pull request because we have deprecated this library in favor of the community fork that @singingfish mentioned above. Please feel free to open your PR there!

**Comment by singingfish** [comment]
just an FYI, thanks to sponsorship from Ziprecruiter, we just released the 1.0 release of WebService::Braintree which gives feature parity with the ruby libraries. https://metacpan.org/release/ZARQUON/WebService-Braintree-1.0

**Pull request closed without merging**
